apiVersion: v1
data:
  MYSQL_DATABASE: {{ .Values.mysql.secret.database | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.secret.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.mysql.secret.user | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}