apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.mysql.appName }}
  name: {{ .Values.mysql.serviceName }}
spec:
  ports:
  - port: {{ .Values.mysql.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.mysql.targetPort }}
  selector:
    app: {{ .Values.mysql.appName }}
