apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resultserver.serviceName }}
spec:
  selector:
    app: {{ .Values.resultserver.selectorApp }}
  ports:
    - protocol: TCP
      port: {{ .Values.resultserver.servicePort }}
      targetPort: {{ .Values.resultserver.targetPort }}
      nodePort: {{ .Values.resultserver.nodePort }}
  type: NodePort