apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webserver.serviceName }}
spec:
  selector:
    app: {{ .Values.webserver.selectorApp }}
  ports:
    - protocol: TCP
      port: {{ .Values.webserver.servicePort }}
      targetPort: {{ .Values.webserver.targetPort }}
      nodePort: {{ .Values.webserver.nodePort }}
  type: NodePort
