apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-deploy
  name: mysql-service
  namespace: b2metric
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-deploy
status:
  loadBalancer: {}
